### ISSUE TITLE
Populate Facebook events from this site

### ISSUE THREAD

**Issue by alexgleason** [liberationphilly/liberationphilly#7]
We need a way to sync data from this site into Facebook.

Wondering if @danielzsandberg or @sbs0414 have any thoughts.

**Comment by danielzsandberg** [comment]
Yes definitely. I suspect we’ll want to do the same for the activist database. So we’ll probably want to expose an HTTP endpoint. Need to do research to find out what kind of plugins, apps, or whatever that we can write on top of the Facebook platform to hit that endpoint on our site.

**Comment by marykatefain** [comment]
Closing because we are planning to shut down our facebook page eventually, so this is not worth spending time on.
